// PRODUCTS

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SHOW_PRODUCT_DETAIL = 'SHOW_PRODUCT_DETAIL';

// CART

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const DECREASE_BY_ONE = 'DECREASE_BY_ONE';

// WISHLIST

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

// CATEGORIES

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const SELECT_CATEGORY_SUCCESS = 'SELECT_CATEGORY_SUCCESS';
